# Dockerfile.worker1 or Dockerfile.worker2
FROM python:3.10-slim

WORKDIR /app

# Ensure requirements.txt is copied to the correct directory inside the container
COPY ./requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the rest of your code into the container
COPY . .

# Set the command to run your worker script (adjust depending on worker version)
CMD python3 worker_new_1.py
